### ISSUE TITLE
How can I override the template files?

### ISSUE THREAD

**Issue by mdjwel** [TemplateInvaders/ti-woocommerce-wishlist#10]
I want to override the WooCommerce Wishlist Plugin's template files. How can I do that?

**Comment by StanMarsh** [comment]
Hi mdjwel,

Our plugin has similar functionality to WooCommerce for template overrides. All you need to do is to copy the necessary template from a Wishlist plugin **\templates** directory into a **\woocommerce** folder of your child-theme.

Regards,
Stan
