### ISSUE TITLE
Do youhave an api endpoint?

### ISSUE THREAD

**Issue by DerryAce** [TemplateInvaders/ti-woocommerce-wishlist#12]
I am building a mobile app using woocommerce as my backend, and I was wondering if I can get the wishlists created on my website to show on the app as well, if you have a json api endpoint that would help.

**Comment by DerryAce** [comment]
Oh and then I forgot to mention when installing the plugin for the first time I get this error SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data. The error can be reproduced when running the install wizard

**Comment by jayporta** [comment]
It's been nearly a year since this was posted. I also need Rest API access. Does it exist?

**Comment by doozy** [comment]
REST API finally released
Documentation:
http://templateinvaders.com/api/wishlist/
