### ISSUE TITLE
Add more parameters for filter `tinvwl_wishlist_button`.

### ISSUE THREAD

**Issue by shrimp2t** [TemplateInvaders/ti-woocommerce-wishlist#14]
I see you add a filter here https://github.com/TemplateInvaders/ti-woocommerce-wishlist/blob/master/public/addtowishlist.class.php#L617

```php
echo apply_filters( 'tinvwl_wishlist_button', $content ); // WPCS: xss ok.
```

It very difficult if I want to add more attributes or modify the existing attributes. Because of all properties of class `TInvWL_Public_AddToWishlist` are private, no ways to access it. It will easier if you add more parameters after $content like the example below:

Example:
```php

echo apply_filters(
    'tinvwl_wishlist_button',
    $content, 
    $icon, 
    $wishlist, 
    $product_id(), 
    $variation_id,
    $action,
    $text
 ); 

```

Example 2:
```php

echo apply_filters(
    'tinvwl_wishlist_button',
    $content, 
    array(
        $icon, 
        $wishlist, 
       $product_id(), 
       $variation_id,
       $action,
       $text
    )
 ); 

```

So the developers will love your plugin because it is very easy to custom wishlist button.

**Comment by doozy** [comment]
Hi @shrimp2t 

Thanks for the idea. The filter extended and update released.
