### ISSUE TITLE
Compatibility issues with WP Rocket

### ISSUE THREAD

**Issue by seldimi** [TemplateInvaders/ti-woocommerce-wishlist#20]
Hello. I'm trying to reach you out for an issue with TI Wishlist and WP Rocket. When "tinv_wishlist" cookie is present, caching doesn't work. That means that if someone logs in and logs out, the "tinv_wishlist" is still blocking the caching.

Can your plugin be implemented so it works with apply_filters( 'rocket_cache_dynamic_cookies', $cookies ), so we still use your awesome plugin with wp rocket and not to have to choose it or yours for any woocommerce shoo?

Thank you

**Comment by seldimi** [comment]
Temporary solution would be on functions.php to be
```
function remove_rocket_cache_cookie($cookies) {
    if (isset($cookies['tinv_wishlist'])) {
        unset($cookies['tinv_wishlist']);
    }
    return $cookies;
}

function logout_redirect765(){
    if (isset($_COOKIE['tinv_wishlistkey'])) {
        unset($_COOKIE['tinv_wishlistkey']);
        setcookie('tinv_wishlistkey', null, -1, '/');
        return true;
    } else {
        return false;
    }
}
add_action('wp_logout','logout_redirect765');
```

**Comment by arunbasillal** [comment]
Hello, I am Arun from WP Rocket. We have a related thread on WP Rocket repo - https://github.com/wp-media/wp-rocket/issues/2244#issuecomment-573894755

Using dynamic cookies as suggested in my reply there might be a solution that works.

**Comment by seldimi** [comment]
Hello.
Unfortunately it didn’t work I’ve tried it couple of times. The only way to fix that was my temporary solution above.

**Comment by doozy** [comment]
Hi @seldimi and @arunbasillal 

Sorry for the delayed reply.

I added a dynamic cookies support and now it works as should with WP Rocket.

**Comment by seldimi** [comment]
I'm afraid that issue still exists but limited.. It doesn't happen any time but some times...

**Comment by doozy** [comment]
Hi @seldimi 

Could you post more details about how exactly you got same issue after the latest update?
