### ISSUE TITLE
Blank page when creating a wishlist using the REST API

### ISSUE THREAD

**Issue by simplenotezy** [TemplateInvaders/ti-woocommerce-wishlist#21]
**Describe the bug**
I am sending a POST request to: `/wp-json/wc/v3/wishlist/create`

I use the JWT Token plugin to authenticate users (not WooCommerce REST API).

I get a blank code 200 response, no matter if I include the authorization code or not.

This is my request:

![image](https://user-images.githubusercontent.com/3786627/75233633-72835f80-57b9-11ea-853a-cd5d3d5c921c.png)

This is my request headers:

![image](https://user-images.githubusercontent.com/3786627/75233654-7adb9a80-57b9-11ea-9321-18d6eece3a65.png)

Why?

**Expected behavior**
A response including the shared key.

**Comment by simplenotezy** [comment]
This does not happen if I include `user_id`, `status` and `title` in the request. I would expect an error code if required fields was not typed in.

How do I create a wishlist for a user, that is NOT logged in?

**Comment by doozy** [comment]
Fixed in the 1.17.0 version
