### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by manueladh** [TemplateInvaders/ti-woocommerce-wishlist#26]
Hello,

I have the TI wishlist plugin on one of my website, every think works perfectly except that I doesn't receive emails from users when they send their wishlist with "ask for an estimate" button.

I can receive mail from contact form, I think it must be something with the plugin and the Divi theme that I am using maybe ?

Thanks in advance for the help

**Comment by doozy** [comment]
The request related to premium version.
