### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by seldimi** [TemplateInvaders/ti-woocommerce-wishlist#29]
Plugin ti-woocommerce-wishlist v1.23.10 → v1.24.1

After update to latest version, Fatal error: Uncaught Error: Class 'TInvWL_PluginExtend' not found

**Comment by doozy** [comment]
Hi @seldimi 

It can happen only when some files corrupted during the update. Try to delete the plugin and install it again.
Maybe you got some file permissions issue, etc.

I'll close this topic because it can't be fixed from our side and mentioned PHP class still available in the latest version.
