### ISSUE TITLE
Admin notice about ti-woocommerce-wishlist-nl_NL 

### ISSUE THREAD

**Issue by phemels** [TemplateInvaders/ti-woocommerce-wishlist#31]
I get an notice in my admin:
Notice: Undefined index: ti-woocommerce-wishlist-nl_NL in /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-pdf-ips-pro/includes/wcpdf-pro-settings.php on line 159

This is caused by the TI wishlist plug-in, it's an translation issue. (was told to me by the WC PDF pro plugin maker)

Can it be fixed?

Installed plugin version is: 1.26.1

**Comment by doozy** [comment]
Hi @phemels 

Please, attach the mentioned file (/home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-pdf-ips-pro/includes/wcpdf-pro-settings.php) to this conversation and we will check for a possible solution.

Thanks!

**Comment by phemels** [comment]
See attachment

>

**Comment by doozy** [comment]
@phemels it doesn't work for replies via email. You need to attach the file via the comments box on Github.

**Comment by phemels** [comment]
See  attachemnt (i needed to download ZIP first, because RAR is not supported)

[wcpdf-pro-settings.zip](https://github.com/TemplateInvaders/ti-woocommerce-wishlist/files/6680450/wcpdf-pro-settings.zip)

**Comment by Spreeuw** [comment]
The error comes from an array composed of `get_available_languages()` and `wp_get_available_translations()` (the latter only available after `require_once( ABSPATH . 'wp-admin/includes/translation-install.php' );`)

So somehow, `ti-woocommerce-wishlist-nl_NL` ends up in the return value of `get_available_languages()` as a language

**Comment by phemels** [comment]
@doozy  The plug-in hs his own NL language :(
![Schermafbeelding 2021-06-21 211933](https://user-images.githubusercontent.com/29940263/122816142-a64f9600-d2d6-11eb-8025-05d1d8b6ebb4.jpg)

**Comment by Spreeuw** [comment]
for context: this is the return value of `get_available_languages()`
@phemels is it possible you misplaced a custom translation file (inside `wp-content/languages` rather than `wp-content/languages/plugins`)?

**Comment by phemels** [comment]
> for context: this is the return value of `get_available_languages()`
> @phemels is it possible you misplaced a custom translation file (inside `wp-content/languages` rather than `wp-content/languages/plugins`)?

@Spreeuw You are right, I think I made an mistake with uploading :(
Sorry "problem" solved.

**Comment by phemels** [comment]
It was caused by an upload mistake of an translation file.
