### ISSUE TITLE
FRAUD

### ISSUE THREAD

**Issue by dhuibh** [TemplateInvaders/ti-woocommerce-wishlist#33]
They will take your money, provide ZERO SUPPORT, say they have refunded when THEY HAVE NOT. These Template Invader thieves are only here to take your money and have been reported for fraud. RUN AWAY! Get a proper Wishlist Plugin from a reputable company.

**Comment by doozy** [comment]
@dhuibh what is wrong with you? 
stop flooding stupid things here! 
you did cancel your subscription and got a refund in full.

 I'll block you next time because your messages aren't true.

**Comment by dhuibh** [comment]
Liar. There was no refund. Ask your fellow criminal Konstantin. This is a pattern with you. Say you refunded but don’t… blame banks and customers. It’s fraud and I will continue to warn people in every forum I can until I get my money. The fraud report has been made to UK Police and is ready to be submitted. What’s it going to be?

**Comment by doozy** [comment]
@dhuibh enough is enough!

Please, go insult people somewhere else. There is the wrong place for your stories and dirty language. 

Good luck!

**Comment by dhuibh** [comment]
Fraudster and scammer Russian criminal clutching at pearls!

You find truth dirty? 

You STEAL. That’s truth.
You LIE. That’s truth.

Oh MY!
