### ISSUE TITLE
Phishlist?

### ISSUE THREAD

**Issue by atirupa** [TemplateInvaders/ti-woocommerce-wishlist#34]
Given that the authors of this plugin have embedded abilities for this to tell them where and when the plugin is running you have to wonder what other information is being collected without your knowledge. Template Invaders are notorious for not doing what they say, providing no support and generally being a thorn in the side of reputable developers so… the wishlists of thousands of YOUR customers along with their information could be at risk.
Use this software with caution!

**Comment by doozy** [comment]
Dear Michael Duff aka @dhuibh 

All your posts will be deleted here.

You are a scammer and trying to tarnish our reputation!
