### ISSUE TITLE
Endpoint to create a wishlist for an unregistered user

### ISSUE THREAD

**Issue by artbotguy** [TemplateInvaders/ti-woocommerce-wishlist#37]
I figured out how to use endpoints for registered users, everything works great: I get a wishlist by id and make other requests by share_key. However, I haven't figured out how to do so in order to initiate a session for an unregistered user. None of the endpoints allows you to create a wishlist (and I'm not talking about the premium endpoint - as I understand it, it is designed so that the user can have more than one wishlist, but here we are talking about basic functionality that is not available in the REST API and so ). I figured out that: TInvWL_Wishlist::add_sharekey_default() delegates:
     - TInvWL_Wishlist::set_sharekey() - sets cookie
     - TInvWL_Wishlist::add() - adds a new vl to the database
But by itself, it is not called and there is no endpoint for it. I found that in TInvWL_Includes_API_Wishlist::wishlist_get_by_user() there is a check to see if the user is logged in and therefore the corresponding script is run or not run. Moreover, if $user_id = 0, an error will not be returned. I thought it would be nice to add an else block to the if block in the try-catch block and write the logic for creating and getting a wishlist for an unregistered user, setting cookies.

**Comment by NikitaLednev** [comment]
I encountered a similar problem, can the developers comment on this?
