### ISSUE TITLE
Critical error during using WP-CLI while TI Wishlist plugin is active

### ISSUE THREAD

**Issue by kamilKrygier** [TemplateInvaders/ti-woocommerce-wishlist#40]
I've found an issue while using WP-CLI and I found out that your plugin causes an critical error (parse error). Problem disappear when plugin is deactivated.
I use two cron jobs at my shop and both cannot be finished without error:
```
cd /{HERE IS PATH TO MY WP} && wp eval-file wp-content/plugins/sixsilver-feeds/fbcatalog-feed.php
cd /{HERE IS PATH TO MY WP} && /usr/local/bin/php wp webp-express convert uploads 
```

I strongly belive that this is not issue caused by me, because this problem occurs also when I disable everything (my code + other plugins). And as I said, it starts to work when I disable TI WooCommerce Wishlist plugin. This blocks my cron jobs :)

# Error:
**Parse error:** syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /{HERE IS PATH TO MY WP}/wp-content/plugins/ti-woocommerce-wishlist/includes/tinvwl.class.php on line 23
**Error:** W witrynie wystąpił błąd krytyczny.Dowiedz się więcej o rozwiązywaniu problemów z WordPressem. W witrynie wystąpił błąd krytyczny. (Which means "There has been a critical error on this website...")

## Enviroment

- Wordpress: 6.2.2
- Woocommerce: 7.9.0
- TI WooCommerce Wishlist: 2.7.3
- Theme: Pro (Child Theme) [Themeco](http://theme.co/)

**Comment by doozy** [comment]
Hi @kamilKrygier 

The error you're encountering is because class properties cannot have a type declaration (such as 'string') in PHP versions prior to 7.4.

Official WordPress.org requirements are:

```
To run WordPress we recommend your host supports:

[PHP](https://www.php.net/) version 7.4 or greater.
[MySQL](https://www.mysql.com/) version 5.7 or greater OR [MariaDB](https://mariadb.org/) version 10.4 or greater.
[HTTPS](https://wordpress.org/news/2016/12/moving-toward-ssl/) support
```

https://wordpress.org/about/requirements/

It looks like you need to update your PHP version.

**Comment by kamilKrygier** [comment]
I duble checked that and I've got PHP version 7.4.33 and Maria-DB 10.5.21
But :) wp-cli used 7.3 version and I somehow forgot to change it while installing it
So... sorry for trouble and thank you for help with debugging the issue 😁
