### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function is_plugin_active_for_network()

### ISSUE THREAD

**Issue by hostingvosting** [TemplateInvaders/ti-woocommerce-wishlist#42]
Fatal error: Uncaught Error: Call to undefined function is_plugin_active_for_network() in C:\xampp\htdocs\freddy\wp-content\plugins\ti-woocommerce-wishlist\ti-woocommerce-wishlist.php:216 Stack trace: #0 C:\xampp\htdocs\freddy\wp-includes\class-wp-hook.php(324): run_tinv_wishlist('') #1 C:\xampp\htdocs\freddy\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #2 C:\xampp\htdocs\freddy\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #3 C:\xampp\htdocs\freddy\wp-settings.php(506): do_action('plugins_loaded') #4 C:\xampp\htdocs\freddy\wp-config.php(96): require_once('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\freddy\wp-load.php(50): require_once('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\freddy\wp-admin\admin.php(34): require_once('C:\\xampp\\htdocs...') #7 C:\xampp\htdocs\freddy\wp-admin\plugins.php(10): require_once('C:\\xampp\\htdocs...') #8 {main} thrown in C:\xampp\htdocs\freddy\wp-content\plugins\ti-woocommerce-wishlist\ti-woocommerce-wishlist.php on line 216

**Comment by IamSZaidH** [comment]
oh it mean if the function does not exist then have to include this
paste this code before line 216.

if ( ! function_exists( 'is_plugin_active_for_network' ) ) {
    require_once ABSPATH . '/wp-admin/includes/plugin.php';
}

**Comment by sytpb** [comment]
Hi , how to solve this issue ?

**Comment by IamSZaidH** [comment]
> Hi , how to solve this issue ?

i solved this issue just download from my forked repository as zip format and upload it to your wordpress.
