### ISSUE TITLE
 Uncaught Error: Call to undefined function is_plugin_active_for_network()

### ISSUE THREAD

**Issue by sytpb** [TemplateInvaders/ti-woocommerce-wishlist#44]
met the same issue as #42, and how to fix it ? 

-------------------------------------------------------

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.4.3
Active theme: Woostify (version 2.2.8)
Current plugin: TI WooCommerce Wishlist (version 2.8.0)
PHP version 8.1.26

Error Details
=============
An error of type E_ERROR was caused in line 216 of the file /home/u981943160/domains/[opamade.com/public_html/wp-content/plugins/ti-woocommerce-wishlist/ti-woocommerce-wishlist.php.](http://opamade.com/public_html/wp-content/plugins/ti-woocommerce-wishlist/ti-woocommerce-wishlist.php.) Error message: Uncaught Error: Call to undefined function is_plugin_active_for_network() in /home/u981943160/domains/[opamade.com/public_html/wp-content/plugins/ti-woocommerce-wishlist/ti-woocommerce-wishlist.php:216](http://opamade.com/public_html/wp-content/plugins/ti-woocommerce-wishlist/ti-woocommerce-wishlist.php:216)
Stack trace:
#0 /home/u981943160/domains/[opamade.com/public_html/wp-includes/class-wp-hook.php(324](http://opamade.com/public_html/wp-includes/class-wp-hook.php(324)): run_tinv_wishlist()
#1 /home/u981943160/domains/[opamade.com/public_html/wp-includes/class-wp-hook.php(348](http://opamade.com/public_html/wp-includes/class-wp-hook.php(348)): WP_Hook->apply_filters()
#2 /home/u981943160/domains/[opamade.com/public_html/wp-includes/plugin.php(517](http://opamade.com/public_html/wp-includes/plugin.php(517)): WP_Hook->do_action()
#3 /home/u981943160/domains/[opamade.com/public_html/wp-settings.php(506](http://opamade.com/public_html/wp-settings.php(506)): do_action()
#4 /home/u981943160/domains/[opamade.com/public_html/wp-config.php(103](http://opamade.com/public_html/wp-config.php(103)): require_once('/home/u98194316...')
#5 /home/u981943160/domains/[opamade.com/public_html/wp-load.php(50](http://opamade.com/public_html/wp-load.php(50)): require_once('/home/u98194316...')
#6 /home/u981943160/domains/[opamade.com/public_html/wp-admin/admin.php(34](http://opamade.com/public_html/wp-admin/admin.php(34)): require_once('/home/u98194316...')
#7 /home/u981943160/domains/[opamade.com/public_html/wp-admin/plugins.php(10](http://opamade.com/public_html/wp-admin/plugins.php(10)): require_once('/home/u98194316...')
#8 {main}

**Comment by IamSZaidH** [comment]
> met the same issue as #42, and how to fix it ?
> 
> When seeking help with this issue, you may be asked for some of the following information: WordPress version 6.4.3 Active theme: Woostify (version 2.2.8) Current plugin: TI WooCommerce Wishlist (version 2.8.0) PHP version 8.1.26
> 
> # Error Details
> An error of type E_ERROR was caused in line 216 of the file /home/u981943160/domains/[opamade.com/public_html/wp-content/plugins/ti-woocommerce-wishlist/ti-woocommerce-wishlist.php.](http://opamade.com/public_html/wp-content/plugins/ti-woocommerce-wishlist/ti-woocommerce-wishlist.php.) Error message: Uncaught Error: Call to undefined function is_plugin_active_for_network() in /home/u981943160/domains/[opamade.com/public_html/wp-content/plugins/ti-woocommerce-wishlist/ti-woocommerce-wishlist.php:216](http://opamade.com/public_html/wp-content/plugins/ti-woocommerce-wishlist/ti-woocommerce-wishlist.php:216) Stack trace: #0 /home/u981943160/domains/[opamade.com/public_html/wp-includes/class-wp-hook.php(324](http://opamade.com/public_html/wp-includes/class-wp-hook.php(324)): run_tinv_wishlist() #1 /home/u981943160/domains/[opamade.com/public_html/wp-includes/class-wp-hook.php(348](http://opamade.com/public_html/wp-includes/class-wp-hook.php(348)): WP_Hook->apply_filters() #2 /home/u981943160/domains/[opamade.com/public_html/wp-includes/plugin.php(517](http://opamade.com/public_html/wp-includes/plugin.php(517)): WP_Hook->do_action() #3 /home/u981943160/domains/[opamade.com/public_html/wp-settings.php(506](http://opamade.com/public_html/wp-settings.php(506)): do_action() #4 /home/u981943160/domains/[opamade.com/public_html/wp-config.php(103](http://opamade.com/public_html/wp-config.php(103)): require_once('/home/u98194316...') #5 /home/u981943160/domains/[opamade.com/public_html/wp-load.php(50](http://opamade.com/public_html/wp-load.php(50)): require_once('/home/u98194316...') #6 /home/u981943160/domains/[opamade.com/public_html/wp-admin/admin.php(34](http://opamade.com/public_html/wp-admin/admin.php(34)): require_once('/home/u98194316...') #7 /home/u981943160/domains/[opamade.com/public_html/wp-admin/plugins.php(10](http://opamade.com/public_html/wp-admin/plugins.php(10)): require_once('/home/u98194316...') #8 {main}


Download from here.
https://github.com/IamSZaidH/ti-woocommerce-wishlist/tree/master
