### ISSUE TITLE
OceanWP compatibility issue - add to wishlist button location

### ISSUE THREAD

**Issue by gacor84** [TemplateInvaders/ti-woocommerce-wishlist#7]
Hi, I've read that you've improved compatibility issues with the OceanWP theme, but I still have problems with the "add to wishlist" button/link when it comes to its position (just for the products list, all works fine for the single product). The button gets stuck on the thumbnail no matter what position I choose, and would like to be able to place it after the "add to basket" button. The site I'm working on is: beautymaxbenidorm.es. Thanks in advance.

Edit: I've tried using the shortcode, but it's still the same.

**Comment by StanMarsh** [comment]
Hi,

In the latest plugin update we've added some necessary actions to output the "Add to Wishlist" button properly. If you look into a source code, you may notice that markup order is different after applying different button positions. But as button position is forced using CSS in the OceanWP theme, it leads to such an issue. I believe the developer of this this theme will correct this ASAP and release a new update.

Meanwhile if you are familiar with CSS, you can easily override styles to fit your needs.

**Comment by gacor84** [comment]
I will look into that, thanks!
